# Generated by Django 6.0.1 on 2026-02-22 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=32, verbose_name='Название категории')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('theme_description', models.TextField(verbose_name='Описание')),
                ('theme_photo', models.ImageField(upload_to='media', verbose_name='Фото')),
                ('theme_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arr.category')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
